name: CF Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Create wrangler.toml
        run: |
          echo 'database_name = "${{secrets.CF_DB_NAME}}"' >> wrangler.toml
          echo 'database_id = "${{secrets.CF_DB_ID}}"'' >> wrangler.toml

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API }}
          accountId: ${{ secrets.CF_ID }}
